### ISSUE TITLE
[Bug] The mongodb configuration information is incorrect

### ISSUE THREAD

**Issue by huxiangquan** [EdurtIO/incubator-datacap#339]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/EdurtIO/datacap/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... the problem doesn't occur with the `server` or `web` themes
- [ ] ... the documentation does not mention anything about my problem
- [ ] ... there are no open or closed issues that are related to my problem

### Description

2023-05-07 05:58:01,243 DEBUG [http-nio-9096-exec-7] org.apache.commons.beanutils.converters.BooleanConverter [AbstractConverter.java:140] Converting 'Boolean' value 'false' to type 'Boolean'
2023-05-07 05:58:01,244 DEBUG [http-nio-9096-exec-7] org.apache.commons.beanutils.converters.BooleanConverter [AbstractConverter.java:162]     No conversion required, value is already a Boolean
2023-05-07 05:58:01,244 DEBUG [http-nio-9096-exec-7] org.apache.commons.beanutils.converters.IntegerConverter [AbstractConverter.java:140] Converting 'Integer' value '30307' to type 'Integer'
2023-05-07 05:58:01,245 DEBUG [http-nio-9096-exec-7] org.apache.commons.beanutils.converters.IntegerConverter [AbstractConverter.java:162]     No conversion required, value is already a Integer
2023-05-07 05:58:01,246 DEBUG [http-nio-9096-exec-7] org.apache.commons.beanutils.converters.StringConverter [AbstractConverter.java:140] Converting 'String' value '192.168.233.20' to type 'String'
2023-05-07 05:58:01,246 INFO [http-nio-9096-exec-7] io.edurt.datacap.spi.connection.JdbcConnection [JdbcConnection.java:70] Connection driver com.mongodb.jdbc.MongoDriver
2023-05-07 05:58:01,247 INFO [http-nio-9096-exec-7] io.edurt.datacap.spi.connection.JdbcConnection [JdbcConnection.java:71] Connection url jdbc:mongodb://192.168.233.20:30307?authSource=admin
2023-05-07 05:58:01,247 INFO [http-nio-9096-exec-7] io.edurt.datacap.spi.connection.JdbcConnection [JdbcConnection.java:73] Connection username with admin password with ***
2023-05-07 05:58:01,250 ERROR [http-nio-9096-exec-7] io.edurt.datacap.spi.connection.JdbcConnection [JdbcConnection.java:87] Connection failed 
java.sql.SQLException: java.lang.IllegalArgumentException: The connection string contains options without trailing slash
	at com.mongodb.jdbc.MongoDriver.getConnectionSettings(MongoDriver.java:370)
	at com.mongodb.jdbc.MongoDriver.getUnvalidatedConnection(MongoDriver.java:193)
	at com.mongodb.jdbc.MongoDriver.connect(MongoDriver.java:165)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)

### Expected behaviour

配置主机IP，端口，后日志输出错误提示无法正确连接到mongodb

### Actual behaviour

配置主机IP，端口，后日志输出错误提示无法正确连接到mongodb。必然出现

### Steps to reproduce

1，数据源管理
2，添加数据源
3，选择mongodb
4，配置主机，端口。自定义认证authsource=admin

### Package versions

docker run -d -p 9909:9096 --name datacap qianmoq/datacap

### Configuration

```yaml
无
```

### System information

- Operating system: ... windows7/windows10/windows11
- Browser: edge

**Comment by qianmoQ** [comment]
Message that will be displayed on users' first issue

**Comment by qianmoQ** [comment]
Is mongo the community open source version or the atlas version

**Comment by huxiangquan** [comment]
> Is mongo the community open source version or the atlas version
i used docker to run it.
docker image version is :
mongo:6.0.5

**Comment by qianmoQ** [comment]
> > Is mongo the community open source version or the atlas version
> > i used docker to run it.
> > docker image version is :
> > mongo:6.0.5

Please use the latest code, the latest code in support of https://github.com/EdurtIO/datacap/pull/343

**Comment by qianmoQ** [comment]
The current problem has been fixed, if it reappears, please try to reopen it and provide details.
