### ISSUE TITLE
mongodb测试连接报Connection failed 

### ISSUE THREAD

**Issue by 18856584989** [EdurtIO/incubator-datacap#395]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/EdurtIO/datacap/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... the problem doesn't occur with the `server` or `web` themes
- [ ] ... the documentation does not mention anything about my problem
- [ ] ... there are no open or closed issues that are related to my problem

### Description

后台服务报错如下
2023-07-11 17:43:37,717 ERROR [http-nio-9096-exec-8] io.edurt.datacap.spi.connection.JdbcConnection [JdbcConnection.java:82] Connection failed
java.sql.SQLException: Connection failed.

Caused by: java.util.concurrent.ExecutionException: com.mongodb.MongoCommandException: Command failed with error 59 (CommandNotFound): 'no such command: 'sqlGetResultSchema'' on server 10.28.149.244:27017. The full response is {"ok": 0.0, "errmsg": "no such command: 'sqlGetResultSchema'", "code": 59, "codeName": "CommandNotFound"}
        at java.util.concurrent.FutureTask.report(FutureTask.java:122)
        at java.util.concurrent.FutureTask.get(FutureTask.java:206)
        at com.mongodb.jdbc.MongoConnection.testConnection(MongoConnection.java:510)
        at com.mongodb.jdbc.MongoDriver.connect(MongoDriver.java:171)
        ... 107 common frames omitted
Caused by: com.mongodb.MongoCommandException: Command failed with error 59 (CommandNotFound): 'no such command: 'sqlGetResultSchema'' on server 10.28.149.244:27017. The full response is {"ok": 0.0, "errmsg": "no such command: 'sqlGetResultSchema'", "code": 59, "codeName": "CommandNotFound"}

mongodb支持jdbc连接吗，是不是mongodb-jdbc驱动包版本2.0.2的问题，mongodb有可用的jdbc最新驱动包吗

### Expected behaviour

连接成功，可以创建mongodb数据库连接

### Actual behaviour

页面报错，弹框展示 Connection failed

### Steps to reproduce

1.创建mongodb连接
2.配置ip和端口，密码，数据库
3.点击测试连接

### Package versions

- Java: `java --version`
- Node: `node --version`
- Npm: `npm -v`
- Server: `./mvnw -Dexec.executable='echo' -Dexec.args='${project.version}' --non-recursive exec:exec -Dorg.slf4j.simpleLogger.defaultLogLevel=WARN -Dorg.slf4j.simpleLogger.log.org.apache.maven.plugins.help=INFO | tail -1`

### Configuration

```yaml
server.port=9096
# Forwarding system preset related errors to custom processing
spring.mvc.throw-exception-if-no-handler-found=true
spring.resources.add-mappings=false
spring.web.resources.add-mappings=true
# Set env for datasource
# 去掉&sessionVariables=sql_mode='STRICT_TRANS_TABLES,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION,PIPES_AS_CONCAT'
spring.datasource.url=jdbc:mysql://10.21.xx.xx:3306/cdc?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&useSSL=false&useOldAliasMetadataBehavior=true&jdbcCompliantTruncation=false
spring.datasource.username=cdc
spring.datasource.password=xx
datacap.security.secret=DataCapSecretKey
datacap.security.expiration=86400000
```

### System information

- Operating system: windows
- Browser: edge
![Uploading 微信图片_20230711175837.png…]()

**Comment by qianmoQ** [comment]
Message that will be displayed on users' first issue

**Comment by 18856584989** [comment]
mongodb支持jdbc连接吗，是不是mongodb-jdbc驱动包版本2.0.2的问题，mongodb有可用的jdbc最新驱动包吗

**Comment by qianmoQ** [comment]
DataCap 是哪个版本呢？经过测试未发现无法连接问题
![image](https://github.com/EdurtIO/datacap/assets/20521442/e0f5605f-0b7c-47fd-9343-b088a9a0949e)

**Comment by 18856584989** [comment]
不好意思 是用了以前老的1.8.0版本 换了最新的1.12.0现在mongo-community可以测试连接成功了
但是数据源展示不了具体的库和集合 接口报The current data source is not supported
这是怎么一回事呢
![image](https://github.com/EdurtIO/datacap/assets/49008485/e6efddd7-bcf9-4387-9811-39f6ee9a337c)

**Comment by qianmoQ** [comment]
> 但是数据源展示不了具体的库和集合 接口报The current data source is not supported

这块数据源管理暂时还未支持呢？请关注我们的下次发版，或者最新的 dev 分支代码，会支持该功能

**Comment by 18856584989** [comment]
好的 感谢
